//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.13 at 08:43:18 PM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:admi.002.001.01", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package iso.std.iso._20022.tech.xsd.admi_002_001;
