spring.application.name=V1
server.port=9090

spring.mvc.pathmatch.matching-strategy=ant-path-matcher

pesa.cert.keystore.password = Vicbank
#pesa.cert.truststore.password = changeit
pesa.cert.tls.version = TLSv1.2
pesa.sign.keys = /opt/bank0054.key
pesa.sign.seal = /opt/bank0054_seal.cert.pem
#pesa.sign.transport = /opt/bank0054-transport.cert.pem
pesa.sign.transport = /opt/bank0054_transport.cert.pem
pesa.sign.chain = /opt/ca_chain.crt.pem

#URLS
#PROD
pesa.url.acmt23= https://api.ips.pesalink.co.ke/iso20022/sync/v1/verification-request
pesa.url.acmt24 = https://api.ips.pesalink.co.ke/iso20022/sync/v1/verification-report
pesa.url.admi011 = https://api.ips.pesalink.co.ke/iso20022/async/v1/event-acknowledgement
pesa.url.pacs008 = https://api.ips.pesalink.co.ke/iso20022/async/v1/credit-transfer
pesa.url.pacs002 =  https://api.ips.pesalink.co.ke/iso20022/async/v1/payment-status-report
pesa.url.pacs028 =  https://api.ips.pesalink.co.ke/iso20022/async/v1/payment-status-request
pesaBulk.url.pacs008 = https://api.ips.pesalink.co.ke/iso20022/async/v1/credit-transfer-bulk

#Signed Messages Output
pesa.output.acmt24=/opt/acmt.024-signed.xml
pesa.output.acmt23=/opt/acmt.023-signed.xml
pesa.output.admi011=/opt/admi.011-signed.xml
pesa.output.pacs008 =/opt/pacs.008-signed.xml
pesa.output.pacs002 =/opt/pacs.002-signed.xml
pesa.output.pacs028 = /opt/pacs.028-signed.xml

#Banks Connected directly to the new switch
pesa.connected.banks = 0001,0003,0012,0014,0019,0023,0031,0063,0065,0074,0054,0053

#Database Credentials
db.class = mmR/m2BcaZWL+kTu86/9mlWmb9E27fsv3QnWKjkWIx4=
db.ip = YiX4CjbsEdbqRCZ2VxwOLg==
db.port = ZWUMLtiLJf0orh1JZA7NGg==
db.database = Ez5WAN6W8WqweKrzm5Za7Q==
db.username= BYXEJVQpS7K0usObaXHiLQ==
db.password =BYXEJVQpS7K0usObaXHiLQ==


#Encryption Keys
enc.key = VcbKey0123456789
enc.initVector =VcbInitVector012

#WSDL properties
pesa.wsdl.username = VCB
pesa.wsdl.password = ZT!O1i1oo%Xf
pesa.wsdl.reg.username = VICTORIA BANK
pesa.wsdl.reg.password = 123456

#Queries
#stmt.api.sql.accountdetails  = SELECT ACCT_NAME FROM TBAADM.GAM WHERE FORACID = ?
#stmt.api.sql.phoneno = SELECT PHONENO FROM CRMUSER.PHONEEMAIL WHERE ORGKEY IN (SELECT CIF_ID FROM tbaadm.gam WHERE FORACID = ?) and rownum=1 AND PHONENO != '(null)'
#pesa.query.insert.hakikisha.account = INSERT IGNORE INTO AccountHakikisha (MsgId,CreDtTm,OriginalPIC,IPSPIC,VrfctnId,AcctToVerify,BeneficiaryBank,VrfctnStatus,VrfctnCode,AccountName) VALUES(?,?,?,?,?,?,?,?,?,?)
#pesa.query.update.hakikisha.account = UPDATE AccountHakikisha SET VrfctnStatus = ?,VrfctnCode = ?,AccountName =? WHERE VrfctnId = ?
#pesa.query.insert.pacs = INSERT IGNORE INTO CreditTransfer (MsgId,CreDtTm,NbOfTxs,SttlmMtd,ClrSysPrtry,PmtTpInfSvcLvl,LclInstrm,CtgyPurp,OriginatorPIC,IPSPIC,EndToEndId,TranAmount,Currency,AccptncDtTm,ChargeBearer,DebtorName,DebtorPhoneNo,DebitAccount,CreditAccount,CreditorName,BeneficiaryBank,Narration,ChargeAmount,ExciseDuty,Pacs002Code,PrincipalAmtFinResponse,ChargeAmtFinResponse,EdutyAmtFinResponse,CreditTranFinResponse,TranType,CreditorPhoneNo,direction,TSQMinutes,RefNumber,PrincipalStan,ChargeStan,EdutyStan) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),?,?,?,?)
#pesa.query.insert.hakikisha.phone = INSERT IGNORE INTO PhoneHakikisha (PhoneToVerify,BankNameAndCode,VrfctnStatus,AccountName) VALUES(?,?,?,?)
#pesa.query.update.pacs = UPDATE CreditTransfer SET CreditorName = ?,Pacs002Code = ?,PrincipalAmtFinResponse = ?,ChargeAmtFinResponse = ?,EdutyAmtFinResponse=?,CreditTranFinResponse = ?,PrincipalStan = ?,ChargeStan = ?,EdutyStan= ? WHERE MsgId = ?
#pesa.query.update.pacs.credit = UPDATE CreditTransfer SET CreditorName = ?,Pacs002Code = ?,CreditTranFinResponse = ?,Creditstan= ? WHERE MsgId = ?
#pesa.query.update.reversal = UPDATE CreditTransfer SET PrincipalReversalResponse = ?,ChargesReversalResponse = ?,EDutyReversalResponse = ?,reversed = ? WHERE MsgId = ?
#pesa.query.checkdormancy = select acct_status  from tbaadm.smt where acid=(Select acid from tbaadm.gam where foracid=?)
#pesa.query.checkopenstatus = select acct_cls_flg from tbaadm.gam where foracid=?
#pesa.tsq.query = SELECT TIMESTAMPDIFF(MINUTE,TSQMinutes,NOW()) FROM CreditTransfer WHERE MsgId=? LIMIT 1
#pesa.query.update.bulk.pacs=UPDATE CreditTransfer set Pacs002Code=? WHERE MsgId = ? and EndToEndId=?
#
#pesa.tsq.query.insert = INSERT IGNORE INTO TSQTable (TimeStamp,OriginatorBank,BeneficiaryBank,MsgId,Status,Amount,Currency,DebitAccount,CreditAccount) VALUES(NOW(),?,?,?,?,?,?,?,?)
#pesa.tsq.query.select = SELECT TimeStamp,OriginatorBank,BeneficiaryBank,Status,Amount,Currency,DebitAccount,CreditAccount FROM TSQTable WHERE MsgId = ? ORDER BY id DESC LIMIT 0, 1
#



stmt.api.sql.accountdetails  = SELECT ACCT_NAME FROM TBAADM.GAM WHERE FORACID = ?
stmt.api.sql.phoneno = SELECT PHONENO FROM CRMUSER.PHONEEMAIL WHERE ORGKEY IN (SELECT CIF_ID FROM tbaadm.gam WHERE FORACID = ?) and rownum=1 AND PHONENO != '(null)'
pesa.query.insert.hakikisha.account = INSERT IGNORE INTO AccountHakikisha (MsgId,CreDtTm,OriginalPIC,IPSPIC,VrfctnId,AcctToVerify,BeneficiaryBank,VrfctnStatus,VrfctnCode,AccountName) VALUES(?,?,?,?,?,?,?,?,?,?)
pesa.query.update.hakikisha.account = UPDATE AccountHakikisha SET VrfctnStatus = ?,VrfctnCode = ?,AccountName =? WHERE VrfctnId = ?
pesa.query.insert.pacs = INSERT IGNORE INTO CreditTransfer (MsgId,CreDtTm,NbOfTxs,SttlmMtd,ClrSysPrtry,PmtTpInfSvcLvl,LclInstrm,CtgyPurp,OriginatorPIC,IPSPIC,EndToEndId,TranAmount,Currency,AccptncDtTm,ChargeBearer,DebtorName,DebtorPhoneNo,DebitAccount,CreditAccount,CreditorName,BeneficiaryBank,Narration,ChargeAmount,ExciseDuty,Pacs002Code,PrincipalAmtFinResponse,ChargeAmtFinResponse,EdutyAmtFinResponse,CreditTranFinResponse,TranType,CreditorPhoneNo,direction,TSQMinutes,RefNumber,PrincipalStan,ChargeStan,EdutyStan) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),?,?,?,?)
pesa.query.insert.hakikisha.phone = INSERT IGNORE INTO PhoneHakikisha (PhoneToVerify,BankNameAndCode,VrfctnStatus,AccountName) VALUES(?,?,?,?)
pesa.query.update.pacs = UPDATE CreditTransfer SET CreditorName = ?,Pacs002Code = ?,PrincipalAmtFinResponse = ?,ChargeAmtFinResponse = ?,EdutyAmtFinResponse=?,CreditTranFinResponse = ?,PrincipalStan = ?,ChargeStan = ?,EdutyStan= ? WHERE MsgId = ?
pesa.query.update.pacs.credit = UPDATE CreditTransfer SET CreditorName = ?,Pacs002Code = ?,CreditTranFinResponse = ?,Creditstan= ? WHERE MsgId = ?
pesa.query.update.reversal = UPDATE CreditTransfer SET PrincipalReversalResponse = ?,ChargesReversalResponse = ?,EDutyReversalResponse = ?,reversed = ? WHERE MsgId = ? 
#pesa.query.checkdormancy = select acct_status  from tbaadm.smt where acid=(Select acid from tbaadm.gam where foracid=?)
pesa.query.update.bulk.pacs=UPDATE CreditTransfer set Pacs002Code=? WHERE MsgId = ? and EndToEndId=?

pesa.query.checkdormancy = select acct_status  from tbaadm.smt where acid=(Select acid from tbaadm.gam where foracid=?) UNION select acct_status  from tbaadm.CAM where acid=(Select acid from tbaadm.gam where foracid=?)

pesa.query.checkopenstatus = select acct_cls_flg from tbaadm.gam where foracid=?
pesa.tsq.query = SELECT TIMESTAMPDIFF(MINUTE,TSQMinutes,NOW()) FROM CreditTransfer WHERE MsgId=? LIMIT 1

pesa.tsq.query.insert = INSERT IGNORE INTO TSQTable (TimeStamp,OriginatorBank,BeneficiaryBank,MsgId,Status,Amount,Currency,DebitAccount,CreditAccount) VALUES(NOW(),?,?,?,?,?,?,?,?)
pesa.tsq.query.select = SELECT TimeStamp,OriginatorBank,BeneficiaryBank,Status,Amount,Currency,DebitAccount,CreditAccount FROM TSQTable WHERE MsgId = ? LIMIT 1
#server.port = 9092

#MySQL Database Properties
database.driver=com.mysql.cj.jdbc.Driver
database.url=jdbc:mysql://
database.user=lUAneQaJdpbv8WipoAj1Jg==
database.port=J9oSA9IYRcs8r3JyiYLnkg==
database.sid=65DHOi9QIR0I5QUz8gUEPH/d29xsq99FDJiHGp1+Wm8=
database.pass=KgJnvGwmLuuzFa31G7mqow==
database.host=RV0Vx+sdZ9G8w3S0ahVxIA==

database.sidproxy=Z3600RECJk6WyLdJTJjT/w==
database.hostproxy=mVkiCdpI2StOtMJJHhTuQw==
database.userproxy=5hN1QRiEI9kR4GekxQkl3A==
database.passproxy=U3MBESCE9al4Xe59hMWTeQ==
database.portproxy=r0PIelzqc0oUhpgZsXkFiA==


#Finacle (Transfer) Configs
#fin.host =172.16.210.102
fin.host = 172.16.200.4
#fin.port = 61146
fin.port=51146
fin.xml = /opt/basic_vcb.xml


#pesa.ws.url = http://172.16.210.195:9093/v1/SimSwitch/SwitchService
pesa.ws.url = http://localhost:9093/v1/SimSwitch/SwitchService
