
package ru.cwt.mgw.lookupdb.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LookupDbWS", targetNamespace = "http://ws.lookupdb.mgw.cwt.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LookupDbWS {


    /**
     * 
     * @param req
     * @return
     *     returns ru.cwt.mgw.lookupdb.ws.OnlineResult
     * @throws LookupDbFault_Exception
     */
    @WebMethod(action = "http://ws.lookupdb.mgw.cwt.ru/LookupDbWS/setDefaultAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setDefaultAccount", targetNamespace = "http://ws.lookupdb.mgw.cwt.ru/", className = "ru.cwt.mgw.lookupdb.ws.SetDefaultAccount")
    @ResponseWrapper(localName = "setDefaultAccountResponse", targetNamespace = "http://ws.lookupdb.mgw.cwt.ru/", className = "ru.cwt.mgw.lookupdb.ws.SetDefaultAccountResponse")
    public OnlineResult setDefaultAccount(
        @WebParam(name = "req", targetNamespace = "")
        OnlineRequest req)
        throws LookupDbFault_Exception
    ;

    /**
     * 
     * @param req
     * @return
     *     returns ru.cwt.mgw.lookupdb.ws.OnlineResult
     * @throws LookupDbFault_Exception
     */
    @WebMethod(action = "http://ws.lookupdb.mgw.cwt.ru/LookupDbWS/updateCustomer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCustomer", targetNamespace = "http://ws.lookupdb.mgw.cwt.ru/", className = "ru.cwt.mgw.lookupdb.ws.UpdateCustomer")
    @ResponseWrapper(localName = "updateCustomerResponse", targetNamespace = "http://ws.lookupdb.mgw.cwt.ru/", className = "ru.cwt.mgw.lookupdb.ws.UpdateCustomerResponse")
    public OnlineResult updateCustomer(
        @WebParam(name = "req", targetNamespace = "")
        OnlineRequest req)
        throws LookupDbFault_Exception
    ;

    /**
     * 
     * @param req
     * @return
     *     returns ru.cwt.mgw.lookupdb.ws.OnlineResult
     * @throws LookupDbFault_Exception
     */
    @WebMethod(action = "http://ws.lookupdb.mgw.cwt.ru/LookupDbWS/deleteCustomer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCustomer", targetNamespace = "http://ws.lookupdb.mgw.cwt.ru/", className = "ru.cwt.mgw.lookupdb.ws.DeleteCustomer")
    @ResponseWrapper(localName = "deleteCustomerResponse", targetNamespace = "http://ws.lookupdb.mgw.cwt.ru/", className = "ru.cwt.mgw.lookupdb.ws.DeleteCustomerResponse")
    public OnlineResult deleteCustomer(
        @WebParam(name = "req", targetNamespace = "")
        OnlineRequest req)
        throws LookupDbFault_Exception
    ;

    /**
     * 
     * @param req
     * @return
     *     returns ru.cwt.mgw.lookupdb.ws.OnlineResult
     * @throws LookupDbFault_Exception
     */
    @WebMethod(action = "http://ws.lookupdb.mgw.cwt.ru/LookupDbWS/registerCustomer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerCustomer", targetNamespace = "http://ws.lookupdb.mgw.cwt.ru/", className = "ru.cwt.mgw.lookupdb.ws.RegisterCustomer")
    @ResponseWrapper(localName = "registerCustomerResponse", targetNamespace = "http://ws.lookupdb.mgw.cwt.ru/", className = "ru.cwt.mgw.lookupdb.ws.RegisterCustomerResponse")
    public OnlineResult registerCustomer(
        @WebParam(name = "req", targetNamespace = "")
        OnlineRequest req)
        throws LookupDbFault_Exception
    ;

    /**
     * 
     * @param req
     * @return
     *     returns ru.cwt.mgw.lookupdb.ws.OnlineCustomerBankListResult
     * @throws LookupDbFault_Exception
     */
    @WebMethod(action = "http://ws.lookupdb.mgw.cwt.ru/LookupDbWS/getCustomerBankList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerBankList", targetNamespace = "http://ws.lookupdb.mgw.cwt.ru/", className = "ru.cwt.mgw.lookupdb.ws.GetCustomerBankList")
    @ResponseWrapper(localName = "getCustomerBankListResponse", targetNamespace = "http://ws.lookupdb.mgw.cwt.ru/", className = "ru.cwt.mgw.lookupdb.ws.GetCustomerBankListResponse")
    public OnlineCustomerBankListResult getCustomerBankList(
        @WebParam(name = "req", targetNamespace = "")
        OnlineCustomerBankListRequest req)
        throws LookupDbFault_Exception
    ;

}
