
package ru.cwt.mgw.lookupdb.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "LookupDbFault", targetNamespace = "http://ws.lookupdb.mgw.cwt.ru/")
public class LookupDbFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private LookupDbFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public LookupDbFault_Exception(String message, LookupDbFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public LookupDbFault_Exception(String message, LookupDbFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.cwt.mgw.lookupdb.ws.LookupDbFault
     */
    public LookupDbFault getFaultInfo() {
        return faultInfo;
    }

}
