
package ru.cwt.mgw.lookupdb.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LookupDbWSService", targetNamespace = "http://ws.lookupdb.mgw.cwt.ru/", wsdlLocation = "http://102.69.239.82:8090/kba/webservices/v2/LookupDbWS?wsdl")
public class LookupDbWSService
    extends Service
{

    private final static URL LOOKUPDBWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOOKUPDBWSSERVICE_EXCEPTION;
    private final static QName LOOKUPDBWSSERVICE_QNAME = new QName("http://ws.lookupdb.mgw.cwt.ru/", "LookupDbWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("http://102.69.239.108:8090/kba/webservices/v2/LookupDbWS?wsdl");
            url = new URL("http://102.69.239.82:8090/kba/webservices/v2/LookupDbWS?wsdl");

        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOOKUPDBWSSERVICE_WSDL_LOCATION = url;
        LOOKUPDBWSSERVICE_EXCEPTION = e;
    }

    public LookupDbWSService() {
        super(__getWsdlLocation(), LOOKUPDBWSSERVICE_QNAME);
    }

    public LookupDbWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOOKUPDBWSSERVICE_QNAME, features);
    }

    public LookupDbWSService(URL wsdlLocation) {
        super(wsdlLocation, LOOKUPDBWSSERVICE_QNAME);
    }

    public LookupDbWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOOKUPDBWSSERVICE_QNAME, features);
    }

    public LookupDbWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LookupDbWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LookupDbWS
     */
    @WebEndpoint(name = "LookupDbWSPort")
    public LookupDbWS getLookupDbWSPort() {
        return super.getPort(new QName("http://ws.lookupdb.mgw.cwt.ru/", "LookupDbWSPort"), LookupDbWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LookupDbWS
     */
    @WebEndpoint(name = "LookupDbWSPort")
    public LookupDbWS getLookupDbWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.lookupdb.mgw.cwt.ru/", "LookupDbWSPort"), LookupDbWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOOKUPDBWSSERVICE_EXCEPTION!= null) {
            throw LOOKUPDBWSSERVICE_EXCEPTION;
        }
        return LOOKUPDBWSSERVICE_WSDL_LOCATION;
    }

}
