//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.02 at 08:06:44 AM EAT 
//


package iso.std.iso._20022.tech.xsd.pacs_002_001_bulk;

import javax.xml.bind.annotation.*;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the iso.std.iso._20022.tech.xsd.pacs_002_001 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iso.std.iso._20022.tech.xsd.pacs_002_001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt }
     * 
     */
    public Document.FIToFIPmtStsRpt createDocumentFIToFIPmtStsRpt() {
        return new Document.FIToFIPmtStsRpt();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts createDocumentFIToFIPmtStsRptTxInfAndSts() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRef() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAcct }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAcct createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefCdtrAcct() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAcct();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAcct.Id }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAcct.Id createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefCdtrAcctId() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAcct.Id();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Cdtr }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Cdtr createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefCdtr() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Cdtr();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAgt }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAgt createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefCdtrAgt() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAgt();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAgt.FinInstnId }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAgt.FinInstnId createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefCdtrAgtFinInstnId() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAgt.FinInstnId();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAgt }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAgt createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefDbtrAgt() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAgt();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAgt.FinInstnId }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAgt.FinInstnId createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefDbtrAgtFinInstnId() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAgt.FinInstnId();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAcct }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAcct createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefDbtrAcct() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAcct();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAcct.Id }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAcct.Id createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefDbtrAcctId() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAcct.Id();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefDbtr() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefDbtrPty() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty.Id }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty.Id createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefDbtrPtyId() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty.Id();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty.Id.OrgId }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty.Id.OrgId createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefDbtrPtyIdOrgId() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty.Id.OrgId();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.PmtTpInf }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.PmtTpInf createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefPmtTpInf() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.PmtTpInf();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.SttlmInf }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.SttlmInf createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefSttlmInf() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.SttlmInf();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf createDocumentFIToFIPmtStsRptTxInfAndStsStsRsnInf() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Orgtr }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Orgtr createDocumentFIToFIPmtStsRptTxInfAndStsStsRsnInfOrgtr() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Orgtr();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Orgtr.Id }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Orgtr.Id createDocumentFIToFIPmtStsRptTxInfAndStsStsRsnInfOrgtrId() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Orgtr.Id();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Orgtr.Id.OrgId }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Orgtr.Id.OrgId createDocumentFIToFIPmtStsRptTxInfAndStsStsRsnInfOrgtrIdOrgId() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Orgtr.Id.OrgId();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.GrpHdr }
     * 
     */
    public Document.FIToFIPmtStsRpt.GrpHdr createDocumentFIToFIPmtStsRptGrpHdr() {
        return new Document.FIToFIPmtStsRpt.GrpHdr();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.GrpHdr.InstdAgt }
     * 
     */
    public Document.FIToFIPmtStsRpt.GrpHdr.InstdAgt createDocumentFIToFIPmtStsRptGrpHdrInstdAgt() {
        return new Document.FIToFIPmtStsRpt.GrpHdr.InstdAgt();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.GrpHdr.InstdAgt.FinInstnId }
     * 
     */
    public Document.FIToFIPmtStsRpt.GrpHdr.InstdAgt.FinInstnId createDocumentFIToFIPmtStsRptGrpHdrInstdAgtFinInstnId() {
        return new Document.FIToFIPmtStsRpt.GrpHdr.InstdAgt.FinInstnId();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.GrpHdr.InstgAgt }
     * 
     */
    public Document.FIToFIPmtStsRpt.GrpHdr.InstgAgt createDocumentFIToFIPmtStsRptGrpHdrInstgAgt() {
        return new Document.FIToFIPmtStsRpt.GrpHdr.InstgAgt();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.GrpHdr.InstgAgt.FinInstnId }
     * 
     */
    public Document.FIToFIPmtStsRpt.GrpHdr.InstgAgt.FinInstnId createDocumentFIToFIPmtStsRptGrpHdrInstgAgtFinInstnId() {
        return new Document.FIToFIPmtStsRpt.GrpHdr.InstgAgt.FinInstnId();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.OrgnlGrpInfAndSts }
     * 
     */
    public Document.FIToFIPmtStsRpt.OrgnlGrpInfAndSts createDocumentFIToFIPmtStsRptOrgnlGrpInfAndSts() {
        return new Document.FIToFIPmtStsRpt.OrgnlGrpInfAndSts();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.FctvIntrBkSttlmDt }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.FctvIntrBkSttlmDt createDocumentFIToFIPmtStsRptTxInfAndStsFctvIntrBkSttlmDt() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.FctvIntrBkSttlmDt();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.IntrBkSttlmAmt }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.IntrBkSttlmAmt createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefIntrBkSttlmAmt() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.IntrBkSttlmAmt();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.RmtInf }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.RmtInf createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefRmtInf() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.RmtInf();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Purp }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Purp createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefPurp() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Purp();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAcct.Id.Othr }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAcct.Id.Othr createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefCdtrAcctIdOthr() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAcct.Id.Othr();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Cdtr.Pty }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Cdtr.Pty createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefCdtrPty() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Cdtr.Pty();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAgt.FinInstnId.Othr }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAgt.FinInstnId.Othr createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefCdtrAgtFinInstnIdOthr() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.CdtrAgt.FinInstnId.Othr();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAgt.FinInstnId.Othr }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAgt.FinInstnId.Othr createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefDbtrAgtFinInstnIdOthr() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAgt.FinInstnId.Othr();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAcct.Id.Othr }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAcct.Id.Othr createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefDbtrAcctIdOthr() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.DbtrAcct.Id.Othr();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty.CtctDtls }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty.CtctDtls createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefDbtrPtyCtctDtls() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty.CtctDtls();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty.Id.OrgId.Othr }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty.Id.OrgId.Othr createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefDbtrPtyIdOrgIdOthr() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.Dbtr.Pty.Id.OrgId.Othr();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.PmtTpInf.SvcLvl }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.PmtTpInf.SvcLvl createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefPmtTpInfSvcLvl() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.PmtTpInf.SvcLvl();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.PmtTpInf.LclInstrm }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.PmtTpInf.LclInstrm createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefPmtTpInfLclInstrm() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.PmtTpInf.LclInstrm();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.PmtTpInf.CtgyPurp }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.PmtTpInf.CtgyPurp createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefPmtTpInfCtgyPurp() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.PmtTpInf.CtgyPurp();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.SttlmInf.ClrSys }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.SttlmInf.ClrSys createDocumentFIToFIPmtStsRptTxInfAndStsOrgnlTxRefSttlmInfClrSys() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.OrgnlTxRef.SttlmInf.ClrSys();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Rsn }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Rsn createDocumentFIToFIPmtStsRptTxInfAndStsStsRsnInfRsn() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Rsn();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Orgtr.Id.OrgId.Othr }
     * 
     */
    public Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Orgtr.Id.OrgId.Othr createDocumentFIToFIPmtStsRptTxInfAndStsStsRsnInfOrgtrIdOrgIdOthr() {
        return new Document.FIToFIPmtStsRpt.TxInfAndSts.StsRsnInf.Orgtr.Id.OrgId.Othr();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.GrpHdr.InstdAgt.FinInstnId.Othr }
     * 
     */
    public Document.FIToFIPmtStsRpt.GrpHdr.InstdAgt.FinInstnId.Othr createDocumentFIToFIPmtStsRptGrpHdrInstdAgtFinInstnIdOthr() {
        return new Document.FIToFIPmtStsRpt.GrpHdr.InstdAgt.FinInstnId.Othr();
    }

    /**
     * Create an instance of {@link Document.FIToFIPmtStsRpt.GrpHdr.InstgAgt.FinInstnId.Othr }
     * 
     */
    public Document.FIToFIPmtStsRpt.GrpHdr.InstgAgt.FinInstnId.Othr createDocumentFIToFIPmtStsRptGrpHdrInstgAgtFinInstnIdOthr() {
        return new Document.FIToFIPmtStsRpt.GrpHdr.InstgAgt.FinInstnId.Othr();
    }

}
